# Generated by Django 3.2 on 2022-09-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
    ]
